### ISSUE TITLE
[help request] pdx.edu projects cs333 project 5

### ISSUE THREAD

**Issue by arshavindn** [tedder/pdx-edu#1]
Hi. I'm a student and my teacher deliveries us this as course mini project. But I can't run MyProgram in project 5, of course I compliled it to binary file and added it into Blitz DISK. I've read through Blitz documents and can't find any instruction that shows how to run it. Could you please help me?

**Comment by tedder** [comment]
Can you send me the course/project guidelines?

**Comment by arshavindn** [comment]
It is project 5 http://web.cecs.pdx.edu/~harry/Blitz/OSProject/p5/proj5.htm
I'm just trying to run MyProgram but I still have not done yet

**Comment by tedder** [comment]
huh. I have no idea.

**Comment by arshavindn** [comment]
oh, what a shame. Did you do it when you went to university?
